### ISSUE TITLE
[PE-D][Tester A] Finding by birthday is unintuitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-4/tp#161]
When using the find function, the user is unable to find by birth month.

![Screenshot 2024-11-08 164128.png](https://raw.githubusercontent.com/1st2GetThisName/ped/main/files/555ff1c1-8e46-4a4b-b089-4c224c972823.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: 1st2GetThisName/ped#4

**Comment by fymbc** [comment]
Thank you for pointing this out, we will plan for this enhancement in the future!
