### ISSUE TITLE
[PE-D][Tester E] Add command results in person having an impractically large age

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-4/tp#163]
![bug 10.png](https://raw.githubusercontent.com/cshao02/ped/main/files/aac67c5e-41a7-4a76-93b2-7a28eeed54c0.png)

As seen from the screenshot, it is possible to add someone with age 224, which is impractical, since no person has ever lived to such an age.

Perhaps when adding a person, the birthday year can be restricted to a minimum value such that such ages will not be allowed.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: cshao02/ped#7

**Comment by AlphaPyke** [comment]
we do not intend to restrict age in such a manner, we believe that as long as it isn't negative it is acceptable
