### ISSUE TITLE
[PE-D][Tester B] Delete command does not show "invalid syntax error" for extra prefixes added

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-4/tp#184]
### When extra prefixes are entered, the DELETE command shows "Invalid index" error rather than invalid command syntax error

![image.png](https://raw.githubusercontent.com/Anvita2110/ped/main/files/fc4f56f2-5caf-40b0-bc41-a3e3dd1ebb51.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Anvita2110/ped#8

**Comment by AlphaPyke** [comment]
same as #212
