### ISSUE TITLE
[PE-D][Tester A] Developer Guide broken br tag

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-4/tp#185]
Test case 2 of adding a person has a broken br tag, resulting in "<br" being written instead of a new line between the testcase and the expected value.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: 1st2GetThisName/ped#5

**Comment by AlphaPyke** [comment]
same as #214
