### ISSUE TITLE
[PE-D][Tester B] Paid Command execution does not change the value in right panel

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-4/tp#190]
### Changes done by paid command is not reflected in right panel unless reselected

![image.png](https://raw.githubusercontent.com/Anvita2110/ped/main/files/f96bec23-b42c-4944-a76d-d4bc6024a806.png)

### After execution, still displays last shown frequency value
---
![image.png](https://raw.githubusercontent.com/Anvita2110/ped/main/files/63a47f5e-c833-4bd2-ba5f-85df46377541.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Anvita2110/ped#9

**Comment by Shantaa** [comment]
Issue already highlighted as a Known Issue in the UG, under Viewing a Client's Details.
