### ISSUE TITLE
[PE-D][Tester A] Three buttons at the bottom of client details are obsolete

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-4/tp#200]
The user guide gives no mention of what those buttons are supposed to mean, if they're supposed to be labels (in which case maybe you should use shapes?), etc. They also do not appear to be editable, nor do they respond to the client's age.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: 1st2GetThisName/ped#7

**Comment by Shantaa** [comment]
Same as #216, will close this as they called it obsolete and I don't like that
