### ISSUE TITLE
[PE-D][Tester C] Feature that don't fit well with the product

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-4/tp#209]
There is this feature where financial advisors can enable or diable visuals by clicking on the tick button.

![image.png](https://raw.githubusercontent.com/IanCheah/ped/main/files/991c1550-f8b9-4429-b8ef-f602e8482e03.png)
However, the application is supposed to be optimized for CLI. I would suggest that this functionality being controlled by command typed in the CLI instead. This is because switching from CLI to mouse back to CLI again can be very frustrating for users that prefer CLI.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: IanCheah/ped#12

**Comment by fymbc** [comment]
Thank you for your suggestion! We can plan this as a feature enhancement.

Our current design consideration is that as we do not foresee the users constantly toggling this additional function, it is reasonable to make it clickable, and leave the commands to be centric around the core functions that operate the contact book. Additionally, as it is a one-click step, this is in line with the original copy URL for help designed for AB3. This is something we believe is well within constraints.
