### ISSUE TITLE
[PE-D][Tester B] All numeric names should have thrown an error

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-4/tp#222]
### All numeric names should have thrown an error because there exists no user with name "9278365" in this whole world!
---
![image.png](https://raw.githubusercontent.com/Anvita2110/ped/main/files/236f7718-a8fa-4b40-a0fb-185aa1f31fd3.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Anvita2110/ped#20

**Comment by AlphaPyke** [comment]
we intend to make name as flexible as possible hence this will not be considered
