### ISSUE TITLE
[PE-D][Tester B] Minimum Screen Resolution does not show Command entering and result panel

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-4/tp#223]
### Suggestion: Minimum resolution window should show all the panels currently in it
---
![image.png](https://raw.githubusercontent.com/Anvita2110/ped/main/files/7645e3ee-8001-482d-8d1b-e81524ee6387.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Anvita2110/ped#21

**Comment by Shantaa** [comment]
Added into "Known Issues" section in the UG, @AlphaPyke can consider adding as an enhancement into the DG as well.
