### ISSUE TITLE
[PE-D][Tester B] Find feature shows different error for invalid values given by users

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-4/tp#229]
### When all numeric or all alphabetic values are entered for name prefix and phone number prefix respectively, it should have shown "Invalid syntax error" rather than "showing result as - 0 listed!"

![image.png](https://raw.githubusercontent.com/Anvita2110/ped/main/files/8f2a4cd4-b4d3-4c74-965f-bf93eda5109a.png)
![Screenshot 2024-11-08 191846.png](https://raw.githubusercontent.com/Anvita2110/ped/main/files/533128fe-10a6-4d61-a383-09792f3b1fcd.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Anvita2110/ped#27

**Comment by fymbc** [comment]
Find command's parameters are not subject to the same strictness as other keywords as we want to give users flexibility to search for what they want, as there is no extra value in restricting their inputs.

Please see more on overzealous input validation [here](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#feature-flaws-2).
