### ISSUE TITLE
[PE-D][Tester D] Different clients with same email seem enological

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F14b-4/tp#230]
Steps to reproduce:

1. add multiple clients with same emails

Problematic behavior: in reality, it seem unlikely that multiple clients with same emails

![Screenshot 2024-11-08 at 7.53.18 PM.png](https://raw.githubusercontent.com/SamsonChew/ped/main/files/52a2b38e-a25b-49a1-a220-31d9c71011b2.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: SamsonChew/ped#23

**Comment by Justin-Aw46** [comment]
Rejected. We leave it up to the user.
