### ISSUE TITLE
Adjust paid/unpaid mechanisms

### ISSUE THREAD

**Issue by meatyturtle** [AY2425S1-CS2103T-F14b-4/tp#73]
Add functionality to automatically call `unpaid` command 
Duration - each Person has a new Payment Frequency attribute (enum -1, 3, 6, 12 / array?)
date does not matter, only count number of months 
frequency is hard coded upon instantiation, late payment does not affect the next date the payment is due 

working under the assumption that client does not pay late

provide confirmation window prompting user, containing next payment date

**Comment by fymbc** [comment]
Closed from #78
